# Generated by Django 5.1.6 on 2025-03-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_remove_book_authors_remove_book_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default='0.0'),
        ),
    ]
